### ISSUE TITLE
App automatically reverts from manual to non-manual mode after one session

### ISSUE THREAD

**Issue by lgtout** [samcv/brainworkshop#27] opened 2020-05-23 20:51 UTC
The app is automatically reverting from manual to non-manual mode after one session of manual mode.  This started happening after I updated master from commit `ea817f7` to tag `v5.0`.  To remedy, I checked out commit `ea817f7` again.   I'm running the app on MacBook Pro 2018 v10.15.4.

To reproduce:
Start the app.
Switch to manual mode.
Play a session.
When the session is complete, notice that the app no longer says "Manual mode: ..." at the top of the window.
Expected: The app should continue in manual mode until explicitly switched to non-manual mode by the user.

**Comment by xantares** [comment] 2020-05-24 07:55
I cannot reproduce with master.
The game should only go back to default when closing the game selection menu.
But there not much commits since ea817f7, can you try reverting 1febda0 ?

**Comment by lgtout** [comment] 2020-05-27 00:13
@xantares Sorry, my mistake.  It's not that the app is reverting to non-manual mode.  The problem is that in manual mode, if you increase the n-back, the n-back reverts to the original value at the end of the session.  Please see if you can reproduce that.  Thanks.

**Comment by xantares** [comment] 2020-05-27 07:48
d35f205ac15e055180a91d7e94967b6e970a68b2

**Closed by xantares** 2020-05-27 07:48 UTC
